### ISSUE TITLE
Clean up pager service

### ISSUE THREAD

**Issue by mvar** [ongr-io/FilterManagerBundle#115]
We should consider to remove all UI related logic ("max pages", "pages" range, etc).

**Comment by saimaz** [comment]
I'm not sure its good to remove it completely. We could provide a way to extend our pagination template like all other bundles does and provide simple bootstrap style pagination. What would be more usefull is to add more blocks in our pagination template for easier.

**Comment by saimaz** [comment]
Well, pager filter is very usefull. The only thing what we can get rid of is templating part. IMO we should just leave the data pass and thats it. User anyway will override template by himself..
