### ISSUE TITLE
Refactor custom filters configuration

### ISSUE THREAD

**Issue by mvar** [ongr-io/FilterManagerBundle#122]
Current configuration for custom filters is too complicated. To use single custom filter with multiple filter managers user must add multiple tags (single tag for each manager). 

We should leave single tag here with "filter name" attribute and create alias `ongr_filter_manager.FILTER_NAME`, so custom filter could be used in configuration like any others.

Another idea: we could even provide a way to extend configuration tree for custom **filter types**.

**Comment by saimaz** [comment]
Yes the current way how to add a filter is a nonsence. Service tag requirements has to be reduced atleast until filter name, without any manager name requirements. But still this is too complicated.
