### ISSUE TITLE
[SF 2.8] Deprecated initRuntime in PagerExtension

### ISSUE THREAD

**Issue by martiis** [ongr-io/FilterManagerBundle#127]
https://github.com/ongr-io/FilterManagerBundle/blob/c2654c201540f0231d38f822965272596bbae8d5/Twig/PagerExtension.php#L48

``Defining the initRuntime() method in the "ongr_pager" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).
``

**Comment by mvar** [comment]
Relates #126 

@martiis did I understand correctly, that this is just a notice, but not complain that something does not work? Next time please add short description in human language :)

@trandangtri could you please make PR to remove this no longer used method and local class variable `$environment`?

**Comment by martiis** [comment]
@mvar Yes

**Comment by trandangtri** [comment]
@mvar, Yes I did
