### ISSUE TITLE
Add `pretty`option for JSON filter manager action

### ISSUE THREAD

**Issue by murnieza** [ongr-io/FilterManagerBundle#130]
Bundle provides default [action](https://github.com/ongr-io/FilterManagerBundle/blob/05370ffc7f6af67d25550f6527205f2f6eeebc28/Controller/ManagerController.php#L62) to get response as JSON. It would be useful to have request parameter `pretty` which would make response more human readable.

**Comment by mvar** [comment]
@murnieza that's nice to have, but is it really needed? Nowadays most modern web browsers has console and are able to show JSON in tree format.

**Comment by murnieza** [comment]
Web browsers are not the only clients. 

Yes it's only nice to have, but it is really easy to implement and I think we should do it :)
