### ISSUE TITLE
Naming for custom filter service should not be limited to specific format.

### ISSUE THREAD

**Issue by murnieza** [ongr-io/FilterManagerBundle#136]
Currently every service for custom filter have to follow `ongr_filter_manager.filter.filter_name` naming format because of [this logic](https://github.com/ongr-io/FilterManagerBundle/blob/742fd42b4cc8ac8600a12dbe634299f94ffc089c/DependencyInjection/ONGRFilterManagerExtension.php#L67).

It should not be like that. Consider adding aliases for custom filters or change filters injection logic.

**Comment by murnieza** [comment]
Because of current Symfony limitations custom filter service should be marked as private in order to works as custom filter. 

This does not look like acceptable behaviour for me.

**Comment by saimaz** [comment]
@trandangtri please ask @murnieza for further assistance when you will implement this issue.

**Comment by mvar** [comment]
I can't get custom filter example to work. Please make sure it works after this issue will be resolved.

**Comment by saimaz** [comment]
Already solved in new major version (currently master branch)
