### ISSUE TITLE
relatedSearch for FilterInterface is populated even though it is not necessary

### ISSUE THREAD

**Issue by anho** [ongr-io/FilterManagerBundle#146]
Hi everyone,

during a recent problem on our page we've seen that the ``$relatedSearch`` instance is populated in the ``FiltersManager`` for passing it to ``FilterInterface::preProcessSearch``. But that is done even though for most of the filters that information is not used. In some circumstances that might lead to problems as additional cpu, memory and maybe other resources are consumed. Is there a specific reason for that implementation or are you guys able to fix that problem?

**Comment by murnieza** [comment]
Hi.
As I understood problem is when `preProcessSearch ` method is empty like in [sort filter](https://github.com/ongr-io/FilterManagerBundle/blob/6921be1c07816bac486fd230dc740cd5d76292bf/Filters/Widget/Sort/Sort.php#L65).  In this case it does not make sense to build related search and pass it to `preProcessSearch`.

Are we on the same page? Please give some more details if not.

**Comment by anho** [comment]
Its not necessarily about the ``preProcessSearch`` method being completely empty. It is about when the ``$relatedSearch`` is not used in that method (but other arguments might). I don't fully understand the idea behind the ``RelationInterface`` that might be connected to this problem as well. But as I see it the ``modifySearch`` method is called ``n`` times for every filter (n being the number of all filters in a specific filter manager) resulting in a n^2 complexity. In most of the cases this is really undesirable and the population of the related search should be deferred until that related search is actually needed.

**Comment by murnieza** [comment]
Yes we are aware of this complexity and want to solve this problem.

I'm thinking about introducing method like `isRelatedSearchNeededForPreProcessSearchNeeded()` (with different name of course :) ) to `FilterInterface`.

I believe that problem it self is related to #30.

**Comment by anho** [comment]
It would be cleaner if you would introduce something like ``LazyPopulatedRelatedSearch`` inheriting from the ``Search`` class and call the ``modifySearch`` methods of the related filters when that lazy search is used. This way everybody will benefit from the change immediately without the necessity to adapt their filter classes. Unfortunately that will include inheritance where composition would be preferred as there is no ``SearchInterface`` or similar.
