### ISSUE TITLE
Run tests with different Elasticsearch versions

### ISSUE THREAD

**Issue by mvar** [ongr-io/FilterManagerBundle#150]
After filters in DSL were deprecated, some filters were replaced by queries in this bundle. Most of the filters extends query and reuses the same code, but few filters are different from queries (e.g., `TermFilter` generates different structure than `TermQuery`). To avoid possible bugs we should test this library on both 2.* and 1.* branches of Elasticsearch. I suggest to reuse the same configuration as ESB currently has.

**Comment by saimaz** [comment]
Agree, filter manager is one of the most sensitive components.
