### ISSUE TITLE
Introduce events dispatching on all major actions.

### ISSUE THREAD

**Issue by saimaz** [ongr-io/FilterManagerBundle#157]

**Comment by saimaz** [comment]
Lets start with persist, pre persist, commit and pre commit

**Comment by mvar** [comment]
@saimaz how `persist` and `commit` actions are related to filter manager?

**Comment by saimaz** [comment]
Shit, didnt, notice through phone that is not elasticsearch bundle.

**Comment by saimaz** [comment]
Then it can be build on filters iteration process and it actions. @einorler lookt at the filter interface for the actions.

**Comment by einorler** [comment]
okay
