### ISSUE TITLE
Example of searching in multiple types

### ISSUE THREAD

**Issue by khusseini** [ongr-io/FilterManagerBundle#256]
Hello everyone,

I've been going through the documentation and I couldn't find a way to search more than one document type at once, similar to http://docs.ongr.io/ElasticsearchBundle/search "Example of searching in multiple types". Is it possible to set more than one repository for a filter manager?

**Comment by saimaz** [comment]
There's no way currently to support multiple document types at once. Nether it be in the future. Elasticsearch is going to remove the types support by leaving one type per index.
