### ISSUE TITLE
Support for Symfony 4.x

### ISSUE THREAD

**Issue by janisbiz** [ongr-io/FilterManagerBundle#258]
Hello!

Based on release of https://github.com/ongr-io/FilterManagerBundle/releases/tag/v2.0.0 it is supposed to support sf4, but it doesn't.

Please add support for sf4 in `composer.json`, as code mainly should work fine on sf4.

**Comment by saimaz** [comment]
Not sure it can work with sf4. Have you checked it?

**Comment by einorler** [comment]
Closing due to #260
