### ISSUE TITLE
Swar parametrs

### ISSUE THREAD

**Issue by tfe2012** [ongr-io/FilterManagerBundle#48]
https://github.com/ongr-io/FilterManagerBundle/blob/974dd223034aa29633968f49bdb94224f745423e/Filters/Widget/Search/MatchSearch.php#L31

otherwise you got query like:
"should": [
                {
                    "match": {
                        "search phrase": {
                            "query": "title"
                        }
                    }
                },

**Comment by saimaz** [comment]
@tfe2012 explain with more detail please. @tautrimas maybe you know more about it?

**Comment by Dariusp** [comment]
this bug fixed there https://github.com/ongr-io/FilterManagerBundle/commit/408b63cf93b34e43120cea9a2433f0abc1293fa7 . Please release new version.

**Comment by saimaz** [comment]
Released https://github.com/ongr-io/FilterManagerBundle/releases/tag/v0.5.0
