### ISSUE TITLE
Json encode filters

### ISSUE THREAD

**Issue by norkunas** [ongr-io/FilterManagerBundle#56]
Hello, why the filters doesn't implement JsonSerializable interface ?

**Comment by chyzas** [comment]
Hello, could you please clarify why do you need JsonSerializable?

**Comment by norkunas** [comment]
I use angular for frontend so the filters view is dynamic and i need to return them with each search request.

**Comment by martiis** [comment]
Try using symfony serializer

**Comment by norkunas** [comment]
I thought about that but we have an abstract json response method which accepts data as array

**Comment by martiis** [comment]
You need only to normalize objects, which is a part of symfony serialization process. Check Serializer::normalize() method.

http://api.symfony.com/2.6/Symfony/Component/Serializer/Serializer.html#deserialize()

**Comment by norkunas** [comment]
ok, will try
