### ISSUE TITLE
Exception with ElasticsearchBundle dev-master version in SingleTermChoice

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/FilterManagerBundle#60]
In code:

https://github.com/ongr-io/FilterManagerBundle/blob/2b0cf4cf18a92a4d2a4823fabd4705b2585debc6/Filters/Widget/Choice/SingleTermChoice.php#L80

Exception is thrown:

```
Attempted to call method "isRelevant" on class "ONGR\ElasticsearchBundle\DSL\Filter\TermFilter".
500 Internal Server Error - UndefinedMethodException
```

Exception is thrown, when we upgraded to ESB dev-master in our application.

**Comment by tautrimas** [comment]
Any update on this?

**Comment by martiis** [comment]
@tautrimas can you give us a use case? Because it has only a unit test which can be easily fixed.

**Comment by tautrimas** [comment]
Of course. Any kind of simplest usage of SingleTermChoice will result in Exception, because of returned values. `$relatedSearch->getPostFilters()` returns an object that does not have method `isRelevant`.

This can only be detected with a Functional / Integration testing.

**Comment by martiis** [comment]
Closed by https://github.com/ongr-io/FilterManagerBundle/pull/65
