### ISSUE TITLE
Range filter is exclusive and there is no way to change it to inclusive.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/FilterManagerBundle#79]

**Comment by saimaz** [comment]
Can you give an example of problem you have?

**Comment by GrandLTU** [comment]
We have a slider on range filter and after setting for example 0 - 1000. No items will be shown with value 0 or 1000 while we want them to be shown. I.e. we want query

``` json
{
    "gte": 0,
    "lte": 1000
}
```

not `gt` and `lt`
