### ISSUE TITLE
Tests fails with Symfony 2.7

### ISSUE THREAD

**Issue by asev** [ongr-io/FilterManagerBundle#90]
Tests fails because of new deprecations.
https://travis-ci.org/ongr-io/FilterManagerBundle/builds/64904797

**Comment by martiis** [comment]
This one is coming from ESB

**Comment by saimaz** [comment]
So lets fix this instead of adding restrictions ;)

**Comment by saimaz** [comment]
Everything is fixed. Use ESB v0.10 for symfony 2.7 support.
