### ISSUE TITLE
Custom filter for multiple managers

### ISSUE THREAD

**Issue by asev** [ongr-io/FilterManagerBundle#92]
Hello,
I would like to create a custom filter and use it at multiple managers.
[At this moment I am able to assign only one manager in filter service definition](http://ongr.readthedocs.org/en/latest/components/FilterManagerBundle/filter/custom_filter.html#defining-service). I don't want to duplicate filter definitions, because there will be ~10 managers.
Any ideas how can I achieve or implement this?

**Comment by GrandLTU** [comment]
Try adding multiple tags e.g. :

``` yaml
tags:
  - { name: ongr_filter_manager.filter, manager: foo_filters, filter_name: foo_range }
  - { name: ongr_filter_manager.filter, manager: boo_filters, filter_name: foo_range }
```

**Comment by asev** [comment]
Thanks @GrandLTU. It does not look very nice with 10 managers, but at least it works.

**Comment by saimaz** [comment]
@asev can you give me a more details why you need 10 managers for filters?

**Comment by asev** [comment]
I have different managers for all product list on website:
- search page
- category page
- seller page
- manufacturer page
- vendor page
- etc...

And I have created a custom filter for products boosting (to have higher priority products on top). This filter should be applied on all (or most) managers.

**Comment by Dariusp** [comment]
You can use bundle extension for adding managers. 
```PHP
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.yml');

        $this->addManagersTagsToFilters($container, $config['managers']);
    }

    private function addManagersTagsToFilters(ContainerBuilder $container,array $managers)
    {
        foreach ($container->getDefinitions() as $key => $definition) {
            if ($this->checkIfFilter($key)) {
                $this->appendTagsToFilters($definition, $managers);
            }
        }
    }

    private function checkIfFilter($name) {
        return (strstr($name, 'filter') !== false);
    }

    private function appendTagsToFilters(Definition $definition, $managers)
    {
        $tags = $definition->getTags();
        foreach ($tags as $tagName => $tag) {
            foreach ($tag as $filterTag) {
                foreach ($managers as $manager) {
                    $filterTag['manager'] = $manager;
                    $definition->addTag($tagName, $filterTag);
                }
            }
        }
    }
```
than tags definitions looks like
```YML
tags:
  - { name: ongr_filter_manager.filter,  filter_name: foo_range }
```

**Comment by saimaz** [comment]
After some investigation we will not implement ability somehow add custom filter to several managers by configuration. It's meant to be added via extensio or tagged services through symfony. If we will do this, it will cause many complex issues.. Sorry.
