### ISSUE TITLE
FunctionScore filter

### ISSUE THREAD

**Issue by asev** [ongr-io/FilterManagerBundle#94]
Function score filter for boosting is missing. I'm going to implement it.
Any ideas or suggestions are welcome.

**Comment by saimaz** [comment]
@GrandLTU can you help with this?

**Comment by GrandLTU** [comment]
@asev what is your current progress with this?

**Comment by asev** [comment]
I have implemented simple function score filter to add weight function on some filters at my project.
IMHO real FunctionScoreFilter should have more cases than that.

**Comment by saimaz** [comment]
Ok, it's been a while... Any progress or attempts to create this filter? Can you share some ideas or feedback with us?

**Comment by asev** [comment]
Yes. Actually I needed to do two things:
1. to boost some terms;
2. use decay function on one of the fields.

I have created a [custom filter](https://gist.github.com/asev/19f40dd2a6ea0fc63bd4) for that. But in general [FunctionScoreQuery](https://github.com/ongr-io/ElasticsearchDSL/blob/master/src/Query/FunctionScoreQuery.php) is much more flexible. Almost all function may have their own BuilderInterface. So, I think we will not be able to create such a flexible filter, configurable through yaml service definition.

I suggest to close this issue.

**Comment by saimaz** [comment]
Overall I think its not worth to try somehow invent too complex filter. Its much better to reduce a complexity to add a custom own filters. Then if somebody wants can create FunctionScore filter by own needs.

Proposing to close this issue.
